### ISSUE TITLE
v1.0.0 Is Not In Maven Central

### ISSUE THREAD

**Issue by gresrun** [astefanutti/metrics-aspectj#10]
It looks like the last artifact to make it to Maven Central was RC5. Could you push the v1.0.0 release artifacts? Thanks!

**Comment by astefanutti** [comment]
The artifact groupId has changed to `io.astefanutti.metrics.aspectj` since `1.0.0`. You can get it here now: http://central.maven.org/maven2/io/astefanutti/metrics/aspectj/metrics-aspectj/1.0.0/.

**Comment by gresrun** [comment]
Ok, got it. Sorry I didn't see the change!
