### ISSUE TITLE
Support histogram via return value and expression language

### ISSUE THREAD

**Issue by sampengilly** [astefanutti/metrics-aspectj#13]
I have a use case for the histogram metric in my codebase and would love to see it supported via annotations like the rest. It presents some challenges in execution but there is a way it could work.

The annotation would be processed upon completion of the annotated method rather than around it as it would operate on the return value of the method.

Examples:
```java
@Histogram(name = "return.integer")
public int returnsAnInteger() {
   return randomInt();
   // Histogram::update is called using return value if return type is int
}
```

```java
// Since EL 2.2 arbitrary method calls are supported
// 'return' bean defined in the aspect as the return value of the annotated method
@Histogram(name = "return.customObject", value = "${return.size()}")
public List<String> returnsAList() {
   return listFetchedFromRemoteService();
   // Histogram::update is called using the value obtained via execution 
   // of the provided EL expression (in this case over the return value)
}
```

```java
@Histogram(name = "return.instanceField", value = "${this.currentValue}")
public void returnsNothingButSideEffects() {
   this.setCurrentValue(someInt());
   // Histogram::update is called using the value obtained via execution
   // of the provided EL expression (in this case over the instance)
}
```

Any thoughts on this style? I'd be happy to implement this if it's ok to go in.

**Comment by astefanutti** [comment]
@sampengilly Looks very interesting! I would suggest you to bring that discussion upstream to the Metrics project attention as the annotations and the corresponding contracts are defined in the `metrics-annotation` module. Ideally this should be added into it so that implementations (like Metrics AspectJ, Metrics CDI, Metrics Spring, ...) can rely on it. WDYT?

**Comment by sampengilly** [comment]
Thanks for the clarification, I'll take this issue upstream to the metrics project.
