### ISSUE TITLE
Gradle usage example would be "nice to have".

### ISSUE THREAD

**Issue by paegun** [astefanutti/metrics-aspectj#16]
Maven is by far leading Gradle in terms of usage ( https://gradle.org/maven-vs-gradle ), so it is understandable why Gradle usage is not addressed here (yet).

That said, Gradle is used w/i a significant number of projects, including some that I contribute to, so I have created such an example:
https://github.com/paegun/metrics-aspectj-gradle-example

Please feel free to link to the example or bring such an example under your control so it can more easily remain up-to-date w/ metrics-aspectj .

**Comment by astefanutti** [comment]
Thanks a lot for sharing this example.

I agree it'd be worth documenting Gradle integration within metrics-aspectj. What do you think about adding a _Using Gradle_ section along with the existing Maven and Ant ones?

**Comment by paegun** [comment]
@astefanutti yes, having a `Using Gradle` section sounds great. I just didn't want to add such scope for this project, especially due to the relative usage of Maven versus Gradle.

**Comment by astefanutti** [comment]
Probably a _Using Gradle_ section with a link to your project would be a good compromise to get started with. We can see how we can condense the information in a second step. If that works for you, that'd be great if you could create a PR, otherwise I'll do it ASAP.
